### ISSUE TITLE
Please upload to bintray

### ISSUE THREAD

**Issue by hani** [nwillc/vplugin#1]
Currently the only version available is 1.2, can you please upload the latest version to bintray?

**Comment by nwillc** [comment]
I distribute vplugin using plugins.gradle.org now ... which mirrors to
jcenter automagically.  Take a look at
https://plugins.gradle.org/plugin/com.github.nwillc.vplugin for usage
instructions.

**Comment by nwillc** [comment]
Maybe it doesn't jcenter mirror ... you'll need to add the repo mentioned
in the usage note.

**Comment by nwillc** [comment]
Looks like plugins.gradle.com isn't updating the mavan-metadata.xml
correctly for some reason.  The plugin is there but you need to get the
version from the plugins.gradle.com to access it.  I'm working with them to
figure out the issue but you can get the plugin even now.
